# Generated by Django 5.1 on 2024-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LoginPage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginmodel",
            name="username",
            field=models.EmailField(max_length=50),
        ),
    ]
